// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adfdysfwowafvphwqenv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZmR5c2Z3b3dhZnZwaHdxZW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM2MjUyMjAsImV4cCI6MjA5OTIwMTIyMH0.FCIDcFSm4wWuL1rhqQAVmAXjnXKSggEdtwjBYD1Wa6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});